name: Clojure CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
    env:
        working-directory: ./core
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.469'
      - name: Run Tests
        run: clojure -A:test -m kaocha.runner "$@"
        working-directory: ${{ env.working-directory }}
